name: Build git-annex on MacOS (14, M1)

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  LANG: C.utf-8

jobs:
  build-package:
    runs-on: macos-14
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v6
        with:
          submodules: false

      - name: Checkout git-annex
        # we exclude doc/ -- it has filenames so long that the FS
        # on windows barfs
        # we fetch shallow, assuming the last 6 months still have a
        # usable tag to determine a version
        run: |
          git submodule init git-annex
          git clone --no-checkout --shallow-since 6.month.ago $(git config submodule.git-annex.url) git-annex
          git submodule update --init --recursive --force git-annex

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: "false"

      - name: Set up system
        run: |
          brew install libmagic pkg-config botan
          uv tool install delocate

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true

      - name: Get build version
        id: build-version
        working-directory: ./git-annex
        run: |
          mkdir -p dist
          version="$(git describe HEAD | sed -e 's/-/+git/')"
          arch=x64
          echo "Building $version"
          echo "version=${version}_$arch" >> "$GITHUB_OUTPUT"
          echo "$(git describe HEAD | sed -e 's/-/./' | sed -e 's/-g.*//')" > dist/pypi-version
          uv run --no-project python -c 'from platform import machine; print(f"macosx_14_0_{machine()}")' > dist/platform-tag
          cat dist/platform-tag

      - name: Configure build
        run: |
          echo OSX_MAGIC_FILE="$(brew list --verbose libmagic| grep magic.mgc | head -n 1)" >> "$GITHUB_ENV"
          echo BUILDERCOMMONOPTIONS="" >> "$GITHUB_ENV"
          echo BUILDER=stack >> "$GITHUB_ENV"
          echo GHC="stack ghc --" >> "$GITHUB_ENV"

      - name: Enable building with magic and botan
        working-directory: ./git-annex
        run: |
          perl -pli -e 's/magicmime: false/magicmime: true/' stack-botan.yaml

      - name: Run stack --version
        working-directory: ./git-annex
        run: stack --version

      - name: Run stack config build-files
        working-directory: ./git-annex
        run: stack config build-files

      # At this point, stack.yaml.lock exists, so we can activate the cache
      - name: Enable Stack cache
        uses: actions/cache@v5
        with:
          path: ~/.stack
          key: cache-stack-m1-${{ hashFiles('git-annex/stack.yaml.lock') }}-${{ hashFiles('git-annex/git-annex.cabal') }}
          restore-keys: |
            cache-stack-macos-m1-

      - name: Build dependencies
        working-directory: ./git-annex
        run: stack build --only-dependencies --extra-include-dirs=$PWD --extra-lib-dirs=$PWD --extra-include-dirs=/opt/homebrew/include --extra-lib-dirs=/opt/homebrew/lib

      - name: Update version info for git rev being built.
        working-directory: ./git-annex
        run: |
          stack ghc --no-haddock Build/BuildVersion.hs
          ./Build/BuildVersion > dist/build-version

      - name: Build git-annex
        working-directory: ./git-annex
        run: stack install --no-haddock --local-bin-path .

      - name: Embed magic.mgc
        run: cp -v "$(brew list --verbose libmagic| grep magic.mgc | head -n 1)" ./git-annex

      - name: Build the Python wheel
        run: |
          uv build --wheel

      - name: Build self-contained wheel
        run: |
          delocate-wheel -w tuned -v dist/*.whl
          delocate-listdeps --all tuned/*

      - name: Inspect and install
        run: |
          unzip -l tuned/git_annex-*.whl
          uv venv
          source .venv/bin/activate
          uv pip install tuned/git_annex-*.whl
          ls -lR .venv

      - name: Test git-annex
        # Install the wheel and test that installation
        run: |
          source .venv/bin/activate
          git-annex version
          git-annex test
          git-annex version | grep MagicMime

      - name: PyPi upload
        # only attempt an upload for release tags
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}
        run: uv publish tuned/*
